#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/commands/core/_main.sh"

##? Show all changed files to main
##?
##? Usage:
##?    changed-files
docs::parse "$@"

git diff --name-only main
