#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/commands/core/_main.sh"

##? Show all ignored files
##?
##? Usage:
##?    show-ignored
docs::parse "$@"

git status --ignored -s | grep "\!\!"
