#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Usage:
##?    install

export DOTFILES_PATH="$HOME/.dotfiles"
source "$DOTFILES_PATH/scripts/core/_main.sh"

echo
log::header "🚀 Mr. Mars .dotfiles installer"
echo
"$DOTFILES_PATH/bin/dot" self install