#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Usage:
##?    install

export DOTFILES_PATH="$HOME/.dotfiles"

echo "👋 Welcome to the borjapazr/dotfiles installer!"

"$DOTFILES_PATH/bin/dot" self install