#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Prune all docker stuff
##?
##? Usage:
##?    prune
docs::parse "$@"

containers="$(docker ps -a -q)"
docker stop $containers
yes | docker system prune -a
