#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Prune all docker stuff
##?
##? Usage:
##?    prune

docs::parse "$@"

docker stop $(docker ps -a -q)
yes | docker system prune -a
