#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Stop all docker containers
#?? 1.0.0
##?
##? Usage:
##?   stop_all
docs::parse "$@"

docker ps -a -q | xargs -I_ docker stop "_"
