#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Convert a millisecond timestamp to a date
##?
##? Usage:
##?    timestamp_to_date <timestamp>
docs::parse "$@"

let DATE_FORMATTED=$1/1000

date -d @$DATE_FORMATTED
