#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show all changed files to master
##?
##? Usage:
##?    changed-filed

docs::parse "$@"

git diff --name-only master
