#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Git log filtering
#?? 1.0.0
##?
##? Usage:
##?   pretty-log

docs::eval "$@"

commit=$(
  git log --graph \
    --color=always \
    --date=human \
    --format="%C(auto)%h%d %s %C(black)%C(bold)%ad by %an" |
    fzf --ansi --no-sort \
      --preview '(git diff-tree --no-commit-id --name-status -r {2})' \
      --preview-window right:35%
)

commit_hash=$(echo ${commit} | grep -oP "\b[0-9a-f]{3,}\b")

echo ${commit_hash} | tr -d '\n' | dot system clip copy
