#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Update each repository inside a folder
##?
##? Usage:
##?    pull-all-dirs

docs::parse "$@"

ls | xargs -I{} git -C {} pull
