#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Update each repository inside a folder
##?
##? Usage:
##?    pull-all-dirs
docs::parse "$@"

# shellcheck disable=SC2011
ls | xargs -I{} git -C {} pull
