#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show all broken symlinks in the current directory
##?
##? Usage:
##?    find_broken_symlinks

docs::parse "$@"

find -L . -type l
