#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Flat the current directory
##?
##? Usage:
##?    flat_this_dir
docs::parse "$@"

sudo find . -mindepth 2 -type f -exec mv -i '{}' . ';'
