#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Preview all files (in all folders) for the current directory
##?
##? Usage:
##?    navigate_and_preview_flatten_files
docs::parse "$@"

fzf --preview 'bat --color \"always\" {}'
