#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Shows the size of the current directory
##?
##? Usage:
##?    size_of_directory
docs::parse "$@"

ncdu --color dark -rr -x
