#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Retrieve the certificate bundle for a given server
##?
##? Usage:
##?    get <remote_service_url>
docs::parse "$@"

# openssl s_client -showcerts -connect $1:$2 </dev/null 2>&1 | sed -n -e '/-.BEGIN/,/-.END/ p' | tee >(pbcopy)

step certificate inspect --insecure --bundle --short --format=text $1
echo
echo
step certificate inspect --insecure --bundle --format=pem $1
