#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Kill process named
#?? 1.0.0
##?
##? Usage:
##?    kill_named <process_name>

docs::eval "$@"

ps aux | grep $1 | grep -v grep | grep -v kill_named | awk '{print $2}' | xargs kill -9

echo '🔫' $1 'killed!'
