#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Kill process on port
#?? 1.0.0
##?
##? Usage:
##?    kill_port <process_port>

docs::eval "$@"

fuser -k -n tcp $1

echo '🔫' $1"'s process killed!"
