#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/commands/core/_main.sh"

##? Prune all docker stuff
#?? 1.0.0
##?
##? Usage:
##?   prune
docs::parse "$@"

platform::require docker || exit 1

dot docker stop_all
yes | docker system prune -a
