#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/commands/core/_main.sh"

##? Prints the owner for a port
##?
##? Usage:
##?   port-owner <port>
docs::parse "$@"

platform::require lsof || exit 1

lsof -n -i4TCP:$1 | grep LISTEN
