#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/commands/core/_main.sh"

##? Show open files by an app
##?
##? Usage:
##?   show-app-open-files
##?   show-app-open-files --watch
##?
##? Options:
##?   -h --help   Show this screen.
##?   -w --watch  Watch the changes
docs::parse "$@"

platform::require fzf lsof || exit 1

selected=$(dot system list-opened-apps | fzf)

if $watch; then
  lsof -r 2 -c "$selected" | awk '{print $4 " " $9}'
else
  lsof -c "$selected" | awk '{print $4 " " $9}'
fi
