#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Regenerate package manifests from what's actually installed:
##?  * Brew
##?  * Apt
##?  * Snap
##?
##? Usage:
##?   export
docs::parse "$@"

if platform::is_macos; then
  HOMEBREW_FILE_PATH="$DOTFILES_PATH/dots/os/macos/brew/Brewfile"
elif platform::is_linux; then
  HOMEBREW_FILE_PATH="$DOTFILES_PATH/dots/os/linux/brew/Brewfile"
fi
APT_FILE_PATH="$DOTFILES_PATH/dots/os/linux/apt/packages.txt"
SNAP_FILE_PATH="$DOTFILES_PATH/dots/os/linux/snap/packages.txt"

_brew_export() {
  brew bundle dump --force --no-vscode --no-mas --no-npm --no-describe --file="$HOMEBREW_FILE_PATH"
}

_apt_export() {
  apt-mark showmanual >"$APT_FILE_PATH"
}

_snap_export() {
  snap list | tail -n +2 | awk '{print $1}' >"$SNAP_FILE_PATH"
}

log::info "🎩 Let's export your packages"

if platform::command_exists brew; then
  log::info "📤 Dumping brew packages"
  _brew_export
fi

if platform::command_exists apt-mark; then
  log::info "📤 Dumping apt packages"
  _apt_export
fi

if platform::command_exists snap; then
  log::info "📤 Dumping snap packages"
  _snap_export
fi

log::success "Done! Review the diff before committing."
