#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Import previously dumped packages from:
##?  * Apt
##?  * Brew
##?  * NPM
##?
##? Usage:
##?   import
docs::parse "$@"

APT_FILE_PATH="$DOTFILES_PATH/os/linux/apt/packages.txt"
APT_DESKTOP_FILE_PATH="$DOTFILES_PATH/os/linux/apt/packages-desktop.txt"
SNAP_FILE_PATH="$DOTFILES_PATH/os/linux/snap/packages.txt"
SNAP_DESKTOP_FILE_PATH="$DOTFILES_PATH/os/linux/snap/packages-desktop.txt"
if platform::is_macos; then
  HOMEBREW_FILE_PATH="$DOTFILES_PATH/os/mac/brew/Brewfile"
elif platform::is_linux; then
  HOMEBREW_FILE_PATH="$DOTFILES_PATH/os/linux/brew/Brewfile"
fi
NPM_FILE_PATH="$DOTFILES_PATH/langs/js/global_modules.txt"

_apt_import() {
  if [ -f "$APT_FILE_PATH" ]; then
    xargs sudo apt-get install -y <"$APT_FILE_PATH"

    if platform::is_linux_desktop; then
      xargs sudo apt-get install -y <"$APT_DESKTOP_FILE_PATH"
    fi
  fi
}

_snap_import() {
  if [ -f "$SNAP_FILE_PATH" ]; then
    grep -vE "^(\s*$|#)" "$SNAP_FILE_PATH" | while read line; do
      sudo snap install $line
    done

    if platform::is_linux_desktop; then
      grep -vE "^(\s*$|#)" "$SNAP_DESKTOP_FILE_PATH" | while read line; do
        sudo snap install $line
      done
    fi
  fi
}

_brew_import() {
  if [ -f "$HOMEBREW_FILE_PATH" ]; then
    # This line is 2 times because there are dependencies between brew cask and brew
    brew bundle install --file="$HOMEBREW_FILE_PATH" || true
    brew bundle install --file="$HOMEBREW_FILE_PATH"
  fi
}

_npm_import() {
  if [ -f "$NPM_FILE_PATH" ]; then
    xargs -I_ sudo npm install -g "_" <"$NPM_FILE_PATH"
  fi
}

log::info "🎩 Let's import your packages (this could take a while)"

if platform::command_exists apt-mark; then
  log::info "📥 Installing apt packages"
  _apt_import
fi

if ! platform::is_wsl && platform::command_exists snap; then
  log::info "📥 Installing snap packages"
  _snap_import
fi

if platform::command_exists brew; then
  log::info "📥 Installing brew packages"
  _brew_import
fi

if platform::command_exists npm; then
  log::info "📥 Installing npm packages"
  _npm_import
fi

log::success "Done!"
