alias ..="cd .."
alias ...="cd ../.."
alias ll="exa -l"
alias la="exa -la"
alias cdh="cd ~"
alias cdp="cd ~/Projects"
alias cdr="cd ~/Resources"
alias dotfiles="cd ~/.dotfiles"

# Jump arround
alias j="z"
alias jz="z -i"
alias jc="z -c"
alias jf="z -I"
alias jb="z -b"
alias jbi="z -b -i"
alias jbf="z -b -I"
alias jh="z -I -t ."
alias jzc="jz -c"
