#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/commands/core/_main.sh"

##? Preview all files (in all folders) for the current directory
##?
##? Usage:
##?    navigate_and_preview_flatten_files
docs::parse "$@"

platform::require fzf bat || exit 1

fzf --preview 'bat --color \"always\" {}'
