#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/commands/core/_main.sh"

##? Shows the size of the current directory
##?
##? Usage:
##?    size_of_directory
docs::parse "$@"

platform::require ncdu || exit 1

ncdu --color dark -rr -x
