#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show the public ip
##?
##? Usage:
##?   ip
docs::parse "$@"

dig +short myip.opendns.com @resolver1.opendns.com
