#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES_PATH}/scripts/core/_main.sh"

##? Open files/folders
#?? 0.1.0
##?
##? Usage:
##?    open <args>...
##?
##? Examples:
##?    open http://google.com

docs::eval "$@"

_open() {
   if platform::is_macos; then
      open "$@" & disown
   else
      xdg-open "$@" & disown
   fi
}

_open "${args[@]:-}"
