#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Prints the owner for a port
##?
##? Usage:
##?   port-owner <port>

docs::parse "$@"

lsof -n -i4TCP:$1 | grep LISTEN
