#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/generic.sh"

##? Update symlinks
##?
##? Usage:
##?    link

docs::parse "$@"

log::note "🔗 Applying symlinks..."
generic::apply_common_symlinks