#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/update.sh"

##? Updates submodules, dotfiles and attempts to do some setup
#?? 1.0.0
##?
##? Usage:
##?    update

docs::eval_help "$@"

if platform::is_linux; then
  log::note "🔄 Updating system..."
  ubuntu::update
fi

log::note "🐙 Updating .dotfiles..."
self_update

log::note "🐙 Updating submodules..."
update_submodules

"$DOTFILES_PATH/bin/dot" self link