#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/update.sh"

##? Updates submodules, dotfiles and attempts to do some setup
#?? 1.0.0
##?
##? Usage:
##?    update

docs::eval_help "$@"

log::note "🔄 Updating system..."
update_linux

log::note "🐙 Updating .dotfiles..."
self_update

log::note "🐙 Updating submodules..."
update_submodules

"$DOTFILES_PATH/bin/dot" self link