#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/commands/core/_main.sh"

##? Debug dotfiles
##?
##? Usage:
##?    debug
docs::parse "$@"

file=${DOTFILES_LOG_FILE:-$HOME/dotfiles.log}

tail -f "$file"
