#!/usr/bin/env bash

set -uo pipefail

source "$DOTFILES_PATH/commands/core/_main.sh"

##? Rewrite all dotfiles related bash files to the canonical format
##?
##? Usage:
##?    format
if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  docs::parse "$@"
fi

platform::require shfmt || exit 1

dot::list_bash_files | xargs shfmt -i 2 -w

log::success "Formatted all bash files"
