#!/usr/bin/env bash

source "$DOTFILES_PATH/commands/core/_main.sh"
source "$DOTFILES_PATH/commands/self/utils/install.sh"
source "$DOTFILES_PATH/commands/self/utils/update.sh"

##? Install the dotfiles
##?
##? Usage:
##?    install
docs::parse "$@"

update_system

install_requirements

log::info "🔗 Aplying symlinks"
"$DOTFILES_PATH/bin/dot" links apply | log::file "🔗 Aplying symlinks" || true

if [[ $SHELL != *zsh* ]]; then
  log::info "💻 Setting ZSH as the default shell"
  sudo chsh -s "$(command -v zsh)" "${USER}" | log::file "💻 Setting ZSH as default shell"
fi

log::info "📥 Importing packages"
"$DOTFILES_PATH/bin/dot" package import 2>&1 | log::file "📥 Importing packages"
