#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/commands/core/_main.sh"

##? Kill process on port
##?
##? Usage:
##?    kill_port <process_port>
docs::parse "$@"

platform::require fuser || exit 1

fuser -k -n tcp $1

echo '🔫' $1"'s process killed!"
